### ISSUE TITLE
Direct synthesis of the Triazolopyrazine core

### ISSUE THREAD

**Issue by pennypresident** [OpenSourceMalaria/OSM_To_Do_List#433] opened 2016-09-10 17:25 UTC
@generalgrivas and I, in addition to working on "The Nemesis" will also be working on a direct synthesis of the triazolopyrazine backbone of all of the potential targets. The advantage of this is the two halogens attached to the core which can easily be replaced by whatever substituent the heart desires. This has been done, but not published. We're using the procedure outlined [here](http://malaria.ourexperiment.org/triazolopyrazine_se/11034/Repeat_synthesis_of_5chloro124triazolo43apyrazine_TM_3714.html) and after that the procedure outline [here](http://malaria.ourexperiment.org/triazolopyrazine_se/11287/Synthesis_of_3bromo5chloro124triazolo43apyrazine_AEW_2062.html) to get the halogenated core that we're after.

Currently, we're synthesizing a couple of batches of the hydrazinylpyrazine to work with in later steps.

**Comment by mattodd** [comment] 2016-09-12 00:23
OK, great, but do check out all of [Haochuan's reactions](http://malaria.ourexperiment.org/triazolopyrazine_se/byuser/plus.google.com-109263878592735967907) from a month or so ago - he got there. It'll be great if you can look into this more, and verify/optimise.

**Comment by pennypresident** [comment] 2016-09-12 00:46
Wow, hadn't seen that lab notebook before-- thanks for the link.

**Comment by mattodd** [comment] 2016-09-12 12:13
Just updated the lab notebook with Haochuan's crystal structure files for the bromo-chloro core, [here](http://malaria.ourexperiment.org/triazolopyrazine_se/14562/Crystal_Structure_Files_for_HM_32_the_bromochloroTP_core.html). Haochuan got this on his last day in Sydney and has not been able to upload to the ELN since he got back to Nanjing - hence the delay in uploading these files.

This is a deeply useful molecule that should, as you say, allow for the attachment of a range of groups, not least the amines suggested by Neil Norcross in #390 . If you can replicate the synthesis and use it to diversify the northeast, that'd be highly useful to us all.

**Comment by mattodd** [comment] 2016-09-14 05:17
See also #413. Have archived some of the material in a "synthesis branch" Google Doc on [this page](http://openwetware.org/wiki/OpenSourceMalaria:Synthesis_Branches), which can be added to by you guys @pennypresident or linked to from other sources. Once the chemistry is worked out, to the point that analogs are made using this route, we can add the [chemistry section of the Series wiki](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Synthetic_Chemistry).

**Comment by pennypresident** [comment] 2016-09-30 03:08
We've made the chlorinated core: http://malaria.ourexperiment.org/hcnemesis16/14688/Synthesis_of_5chloro124triazolo43apyrazine_MRLS_23.html

Will proceed with Haochuan's procedure to brominate and then recrystallize: http://malaria.ourexperiment.org/triazolopyrazine_se/14294/Synthesis_of_3bromo5chloro124triazolo43apyrazine_HM_32.html

**Comment by alintheopen** [comment] 2016-10-01 00:43
Hi @pennypresident - fantastic news and it looks just like Haochuan's spectra too. Good luck with the next step! How much material do you have?

**Comment by GeneralGrivas** [comment] 2016-10-02 05:02
@alintheopen ,
@GeneralGrivas here (working with @pennypresident)--we've made about 0.252 g (1.76 mmol) of the chlorinated triazolopyrazine core so far. We will attempt to synthesize again using more starting material to experiment with bromination and aryl chloride substitution.

**Comment by alintheopen** [comment] 2016-10-02 05:46
Great news @GeneralGrivas and @pennypresident - good idea to bring through grams of material ready to start the next steps - maybe you could both put on a 1-2 g reaction of to make the SM and compare yields to make sure that we have developed a robust and reproducible prep? Great work though!

**Comment by mattodd** [comment] 2016-10-04 23:43
Really good @GeneralGrivas @pennypresident - Have we (any of us) made a pure sample of this material that is ready for publication? i.e. do we have something crystalline and pure that will give us a good melting point? Someone needs to take care of this before we publish. now seems like a good time?
@edwintse can you chip in here? Did you have solid evidence that the bromo-chloro-core, when you reacted it with an amine (to substitute the Br) lost the Cl as well (subst by OH)? I think you (Ed) were planning to take this chloro-core, substitute with an alcohol and *then* brominate as an alternative? I think I'm right in saying it's early days with these conclusions, so maybe the best thing to do @GeneralGrivas @pennypresident is to bring all material through to chloro-bromo core as per Haochuan's work and see if you experience the same issue, and whether it can be fixed easily, e.g. by doing the amine substitution of the Br under dry conditions.

**Comment by pennypresident** [comment] 2016-10-05 01:17
@mattodd - Haven't attempted a crystallization of the chlorinated core. We've attempted the bromination using Haochuan's method, but it failed pretty hard, for various reasons. Will post a link to the notebook entry once I get my act together. 

Would it be better to focus on getting a very pure crystalline sample of the chlorinated core, or work on bromination some more? We've got just enough of the chlorinated core left to try some crystallization. We'll have some more of the chlorinated core coming through shortly (we hope).

**Comment by edwintse** [comment] 2016-10-05 01:36
@GeneralGrivas @pennypresident I've not done the Br displacement with an amine myself but did purify Haochuan's attempt at it and it looks like the Cl was displaced with OH during the Br displacement step as the NW side chain wasn't present. I have since attempted to do the nucleophilic displacement of the Cl before bromination, which gave 39% yield. Subsequent bromination also appears to have worked but the 17% yield is quite poor. [here](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/NDQ4LjV8MTUwOS8zNDUvVHJlZU5vZGUvMjA4ODQ4MzY2N3wxMTM4LjU=)

**Comment by alintheopen** [comment] 2016-10-05 01:52
Hi all

@tscmacdonald  got some good data (and his thesis is available [here](http://malaria.ourexperiment.org/uri/8f4)
<img width="428" alt="screen shot 2016-10-05 at 12 50 20 pm" src="https://cloud.githubusercontent.com/assets/2626599/19098623/78e74100-8afa-11e6-9858-75d57ff5af40.png">
<img width="460" alt="screen shot 2016-10-05 at 12 51 05 pm" src="https://cloud.githubusercontent.com/assets/2626599/19098622/78e74c54-8afa-11e6-8125-4151d60943bb.png">

More comments later but just to fill you in :)

**Comment by mattodd** [comment] 2016-10-05 03:11
Nice, thanks @alintheopen . Nice data @tscmacdonald - there are just enough little bumps on the baseline of that 1H spectrum to make me think we ought to obtain a crystalline sample if we can, get CHN and then take the melting point. Do people agree? Is there some Haochuan sample remaining of the bromo-chloro core that we use for the same purpose?

**Comment by pennypresident** [comment] 2016-10-05 18:08
@mattodd -- do you think it might be worth trying some Suzuki reactions here? We've got a few of the proper boron compounds, and it might be neat to see if yield or ease of purification is improved. Thoughts?

**Comment by mattodd** [comment] 2016-10-06 04:33
It's a possibility. I think Plan A ought to be synthesis and characterisation of chloro core, then bromo-chloro core on gram scale, then exploration of the displacement of the bromine selectively. That's the core synthetic challenge. Suzuki conditions are one possibility here, but I think the attachment of amines remains a higher priority at the moment, given how little those compounds have been explored. Haochuan used Pd for the displacement, so you get a little Suzuki flavour to the work :)

**Comment by pennypresident** [comment] 2016-10-07 15:07
Interesting development-- This time on the core synthesis, I used polymer-bound p-TsOH in hopes of having a much cleaner reaction, which it was. The reaction mixture was a deep, clear wine color as opposed to being a thick black mess with the unbound catalyst. Here's the TLC I got, starting, cospot, product: 
![image](https://cloud.githubusercontent.com/assets/21691808/19194969/8212af24-8c7d-11e6-9ad8-a10ef83d57b5.png)
Not sure what the huge spot up the plate is. Almost all of the starting material has been consumed, but there isn't very much product. Here's the TLC from the last, successful reaction:
![image](https://cloud.githubusercontent.com/assets/21691808/19195048/e14efbb4-8c7d-11e6-9dba-02f01033e8bf.png)
any ideas as to what that might be? I wanted to take NMR but the organic chemistry class reserved it for the day. I think @alintheopen mentioned a possible aldehyde side product in one of her notebook entries (can't find it quickly) which it may be.

**Comment by MFernflower** [comment] 2016-10-08 01:58
A nmr of the purified mystery product would be the best but there are a few quick tests you can do for the cho group http://academics.wellesley.edu/Chemistry/chem211lab/Orgo_Lab_Manual/Appendix/ClassificationTests/aldehyde_ketone.html

**Comment by rbroadrup-HC** [comment] 2016-10-08 09:56
Fresh 2,4-DNP stain will be ready for you on if not before return from fall
break.

**Comment by mattodd** [comment] 2016-10-09 12:14
Hi @pennypresident - you're going to load all these TLC pix and observations up to the ELN, right? ;) 
I guess my first reaction would be to ask for the co-spot between this reaction and what you got last time (the product, to be sure the reaction is essentially similar in outcome, and which spot is which) and then suggest purification via column, followed by measurement of the mass yields of the major fractions. If you've a high yield of product, and the large spot ends up being a small mass of material, then we'd have to judge the extent to which we "care" that something else is being formed. If, however, it's a decent amount of another product then we should discover its identity so that we can, next time, minimise it. Polymer-supported H+ obv v nice in terms of synthetic ease.

**Comment by MedChemProf** [comment] 2016-10-11 12:17
@pennypresident It is a little difficult to compare the two TLC's and @mattodd suggestion to co-spot the two reaction products together is a good idea. It seems unlikely to me, but is it possible that the new conditions resulted in only the formylation of the hydrazine to make the formylhydrazide and it has not yet cyclized? Usually it is difficult to not have the 5-membered ring form, but an NMR of the purified spot would be very helpful. If it does happen to be the formylated material, then it may still be possible to cyclize.

**Comment by MFernflower** [comment] 2016-10-12 00:09
@MedChemProf If it did form a aldehyde the DNHP test should show pretty strongly

**Comment by pennypresident** [comment] 2016-10-12 04:40
Right-- finally got around to doing the ELN for 2-4 with the poly-bound catalyst: http://malaria.ourexperiment.org/hcnemesis16/14806/Synthesis_of_5chloro124triazolo43apyrazine_MRLS_24.html
Not much I can do until I get back to school on Friday, but I'll keep this thread and lab notebook updated once I return.

**Comment by MedChemProf** [comment] 2016-10-12 12:02
@pennypresident Thanks for updating the ELN. It was a little tough to tell since not all of the peaks in the NMR were integrated, but to me it looks like your major product is the intermediate shown below [ ClC1=CN=CC(N/N=C/OCC)=N1 ]
![intermediate](https://cloud.githubusercontent.com/assets/14179120/19309114/0d9d9e10-9051-11e6-941d-e61c2eb47d32.jpg)
If isolated separate from the minor product after your column, you should be able to subject it back to the acid catalyzed reaction conditions to force it to more of your desired product.
@MFernflower , in this particular reaction, there is no aldehyde present or formed as a product.

**Comment by MFernflower** [comment] 2016-10-12 15:06
Should be easy to cleave with sulfuric acid @pennypresident  @MedChemProf your ability to read NMR is stunning!

**Comment by alintheopen** [comment] 2016-10-12 21:58
I agree @MedChemProf - and yes, really important to update the ELN @pennypresident so great work!

**Comment by mhc1994** [comment] 2016-10-19 13:34
Hi,@pennypresident! I think for the bromination step, you may get good result by dissolving SM and NBS separately and dropping NBS solution to the solution of SM under reflux. As for the core synthesis, I really appreciate the idea of using polymer-bound TsOH. which would make the subsequent procedure easier.  I would try more catalyst or refluxing for longer time because I in my previous goes, the SM was totally consumed and only the top two spots appeared when no acid was added.Then, by adding the tosylic acid, the product spot appears and the top two were lighter. I think this matches part of the mechanism proposed by Thomas because the final conversion needs acid to generate but the first several steps don't. And since protontation is  an equilibrium I think a little higher concentration of proton will help produce more **37** to get the final product.
![image](https://cloud.githubusercontent.com/assets/20328764/19520122/a8e4bf48-9641-11e6-8e7b-234a7afb78d9.png)

**Comment by MFernflower** [comment] 2016-10-19 15:24
A part of me wonders if its a good idea to change the acid used to TfOH -
its quite a bit stronger and is very stable

**Comment by pennypresident** [comment] 2016-10-20 03:45
Okay, update on the polymer bound reaction: I did a column on the reaction mixture that had a lot of the molecule that @MedChemProf mentioned thanks to his NMR wizardry, and separated that fraction out and resubmitted it to acidic conditions. There was a bit of the core in here (about 40 mg) which seemed to be pretty pure based on NMR. The resubmission seemed to work pretty well, and based on the TLC the ring was indeed closed (compared to the successful 2-3). I did another biotage on this to isolate that fraction, but this time, it reduced to an oil. Not sure what went differently this time. This fraction did indeed appear to be the core. Will take NMR of the oil tomorrow. 
All of this is in the 2-4 ELN.

**Comment by mattodd** [comment] 2016-11-21 12:25
Hi @pennypresident - am I right in thinking that this part of your work is now parked, or are you still working on it. Given the very nice data you obtained, it'd be very good if you can ensure you've publication-quality data for compounds that you know you made. If we're done here, can you provide a few lines of where you were up to, and what the next team ought to be looking at (wherever that team comes from), and then close this Issue, please? I've installed a link to this Issue in the [Synthetic Chemistry section of the wiki](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Alternative_Routes_to_the_Triazolopyrazine_Core) so we don't orphan it.

**Comment by pennypresident** [comment] 2016-11-21 15:54
@mattodd Yep, work is pretty well parked. I underestimated how much more work the second half of physical chemistry would be!

I should be able to get good data on all of these core compounds over US Thanksgiving break. After an expensive fix, the GCMS is running again. 

In summary: 

The first 3 attempts were with crystalline p-TsOH, which produced a fairly messy reaction mixture, but produced a decent product in ~50% yield after a column was run. Note: might be best to do reverse-phase on this. Very low Rf on normal phase, ~0.08. The product was easily separated by the column, no challenges there.

The fourth attempt was with polymer-bound p-TsOH, which resulted in a much cleaner and clearer reaction mixture. Our attempt at this was done in a microwave reactor at 150 C, but only run for 3 hours. Might be best to just do a regular old reflux in toluene for something like 48 hours (the polymer slows down the reaction rate a bit as I recall). There was some of the core made (~50 mg as I recall) in those three hours, which was isolated via column chromatography. The NMR of the this poly-bound synthesis looked a good bit better than the crystalline synthesis, so I think this poly-bound stuff might be worth looking into further. 

There was an attempt made at brominating the core using NBS in chloroform, but that failed completely as far as I can tell. The solvent escaped (but the argon balloon was still full??) so the reaction mixture sans solvent got cooked pretty good. This is definitely incomplete and needs to be tried again.

**Closed** 2016-11-21 15:54 UTC
Labels: Being Synthesised Now, Series 4

**Comment by MFernflower** [comment] 2016-11-21 18:58
Great work! I wonder if there stuch a thing as polymer bound NBS

**Comment by MFernflower** [comment] 2016-11-21 19:14
@pennypresident Found this and thought it could be useful! https://www.researchgate.net/publication/244607909_Microporous_Solids_for_the_Selective_Bromination_of_a_Diterpene_Resin_Acid
